fun_list <- c( "argparser.r",
               "read_data_to_check.r",
               "read_fgs.r",
               "metadata_check.r",
               "spatconv.r",
               "read_dem.r",
               "ccrrt.r",
               "rr_windcorr.r",
               "check_z_against_dem.r",
               "plausibility_test.r",
               "climatological_check.r",
               "buddy.r",
               "fgt.r",
               "sct_resistant.r",
               "sct_dual_r.r",
               "sct_fg_resistant.r",
               "netcdf_util.r",  
               "statistics_util.r",
               "wolff_correction.r",
               "misc_util.r",
               "write_output.r",
               "isolation.r",
               "final_decision.r",
               "debug_util.r")

