load("tmp.rdata")
yo<-yo_sct[ix]
yb<-yo-res[[6]]
ya<-yo-res[[4]]
yav<-yo-res[[5]]
ix00<-which(res[[1]]==0)
ix01<-which(res[[1]]==1)
ix11<-which(res[[1]]==11)
ix12<-which(res[[1]]==12)
print(length(ix00))
print(length(ix01))
print(length(ix11))
print(length(ix12))
png("fig1.png",height=800,width=800)
plot(yo,z[ix],col="gray")
points(yb,z[ix],col="blue")
points(ya,z[ix],col="red")
points(yav,z[ix],col="purple")
points(yo[ix01],z[ix][ix01],pch=4,col="black")
dev.off()
quit()
